server:
  port: 8889

spring:
  application:
    name: config-client
  cloud:
    discovery:
      enabled: true
      serviceId: config-server
    config:
      label: master
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
