server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/ShadowRoland/BaseSpring
          searchPaths: SpringCloudConfig/respo
#          username: username
#          password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
