server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev # dev/sit/prod等。分别对应开发、测试、生产等不同运行环境。

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/basespring?characterEncoding=UTF-8
    username: root
    password: zhouyuqing
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath:sql/schema-${spring.profiles.active:dev}.sql
    #data: classpath:sql/data-${spring.profiles.active:dev}.sql
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml
